[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CASafari"
version = "0.1.9"
description = "A Flask and TwitchIO web application and bot"
readme = "README.md"
authors = [
    { name = "c-astronomy", email = "castronomy@yahoo.com" }
]
license = { text = "AGPL-3.0-only" }
requires-python = ">=3.8"

classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Flask",
    "Topic :: Communications :: Chat",
    "Intended Audience :: Developers"
]

dependencies = [
    "flask>=3.0.0",
    "redis>=5.0.0",
    "redislite>=6.0.0",
    "asqlite>=2.0.0",
    "pycurl>=7.45.0",
    "twitchio[starlette]>=3.3.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
casafari = ["*.json"]

